# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'DateCourse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'TwitterKit'

  # Pods for DateCourse

  target 'DateCourseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DateCourseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
